version: '3'
services:

  #PHP Service
  santex:
    build:
      context: .
      dockerfile: santex.Dockerfile
    image: digitalocean.com/php
    container_name: santex
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: santex
      SERVICE_TAGS: dev
    working_dir: /var/www/santex
    volumes:
      - ./santex-service:/var/www/santex
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./santex-service:/var/www/santex
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
        
#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
