version: '3'

#Docker Networks
networks:
  app-network:

services:

  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    ports:
      - 80:80
      - 443:443
    networks:
      - app-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/serts/:/etc/traefik/certs
      - ./traefik/conf/:/etc/traefik/dynamic

    labels:
      - traefik.enable=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.traefik.rule=hostregexp(`{host:.+}`)
      - traefik.http.routers.traefik.entrypoints=web
      - traefik.http.routers.traefik.middlewares=redirect-to-https



  #PHP Service
  santex:
    build:
      context: .
      dockerfile: santex.Dockerfile
    container_name: santex
    restart: unless-stopped
    tty: true
    volumes:
      - ./santex-service:/var/www/html/santex
      # - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    labels: 
      - traefik.enable=true
      - traefik.http.routers.santex.rule=Host(`santex-service-kr.ru`)
      - traefik.http.routers.santex.tls=true
      - traefik.http.routers.santex.entrypoints=web-secure
      - traefik.http.services.santex-service.loadbalancer.server.port=8080
      
